version: '3.9'

# See the usage instructions in the README.md

services:

    base-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: ubuntu:focal
        image: ${NRP_DOCKER_REGISTRY}/base-ubuntu20-env:${NRP_CORE_TAG}
        command: bash


    nrp-vanilla-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/base-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/vanilla.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-vanilla-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/gazebo.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/base-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env

    xpra-gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/xpra.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/gazebo-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/xpra-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - gazebo-env


    nest-gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/nest.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/gazebo-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - gazebo-env


    xpra-nest-gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/xpra.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/xpra-nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - nest-gazebo-env


    nrp-nest-gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/nrp-nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - nest-gazebo-env


    nrp-xpra-nest-gazebo-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/xpra-nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/nrp-xpra-nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - xpra-nest-gazebo-env



    opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/opensim.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/base-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/opensim-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-env


    tvb-opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/tvb.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/opensim-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - opensim-env


    xpra-tvb-opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/xpra.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/xpra-tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - tvb-opensim-env


    nrp-xpra-tvb-opensim-env:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            target: nrp-core-env
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/xpra-tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/nrp-xpra-tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - xpra-tvb-opensim-env


    base-nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/base.Dockerfile
            args:
                BASE_IMAGE: nvidia/cudagl:11.4.2-base-ubuntu20.04
        image: ${NRP_DOCKER_REGISTRY}/base-nvidia-cuda-ubuntu20-env:${NRP_CORE_TAG}
        command: bash


    nvidia-cuda-env:
        build:
            context: .
            dockerfile: dockerfiles/nvidia_cuda.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/base-nvidia-cuda-ubuntu20-env:${NRP_CORE_TAG}
        image: ${NRP_DOCKER_REGISTRY}/nvidia-cuda-ubuntu20-env:${NRP_CORE_TAG}
        command: bash
        depends_on:
        - base-nvidia-cuda-env
