version: '3.9'

# See the usage instructions in the README.md

services:


    nrp-vanilla:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/base-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/vanilla.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-vanilla-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-gazebo:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/gazebo-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/gazebo.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-gazebo-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-xpra-gazebo:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/xpra-gazebo-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/gazebo.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-xpra-gazebo-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-xpra-nest-gazebo:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/xpra-nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/nest-gazebo.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-xpra-nest-gazebo-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-nest-gazebo:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/nest-gazebo-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/nest-gazebo.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-nest-gazebo-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-opensim:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/opensim-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/opensim.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-opensim-ubuntu20:${NRP_CORE_TAG}
        command: bash



    # nrp-tvb:
    #     build:
    #         context: .
    #         dockerfile: dockerfiles/nrp-core.Dockerfile
    #         args:
    #             BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/tvb-ubuntu20-env:${NRP_CORE_TAG}
    #             CMAKE_CACHE_FILE: .ci/cmake_cache/tvb.cmake
    #     image: ${NRP_DOCKER_REGISTRY}/nrp-tvb-ubuntu20:${NRP_CORE_TAG}
    #     command: bash



    nrp-tvb-opensim:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/opensim.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-tvb-opensim-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-xpra-tvb-opensim:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/xpra-tvb-opensim-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/opensim.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-xpra-tvb-opensim-ubuntu20:${NRP_CORE_TAG}
        command: bash



    nrp-nvidia-cuda:
        build:
            context: .
            dockerfile: dockerfiles/nrp-core.Dockerfile
            args:
                BASE_IMAGE: ${NRP_DOCKER_REGISTRY}/nvidia-cuda-ubuntu20-env:${NRP_CORE_TAG}
                CMAKE_CACHE_FILE: .ci/cmake_cache/nrp-nvidia-cuda.cmake
        image: ${NRP_DOCKER_REGISTRY}/nrp-nvidia-cuda-ubuntu20:${NRP_CORE_TAG}
        command: bash

