#!/usr/bin/env bash

export NRP=/home/${USER}/.local/nrp
export PYTHONPATH=${NRP}/lib/python3.8/site-packages:$PYTHONPATH
export LD_LIBRARY_PATH=${NRP}/lib:$LD_LIBRARY_PATH
export PATH=$PATH:${NRP}/bin
export PATH=$PATH:${HOME}/nrp-core/examples/unity:${HOME}/nrp-core/examples/roboskate
